name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: install tauri
      #run: cargo install create-tauri-app --locked
    - name: update
      run: sudo apt-get update
    - name: tauri essentials
      run: sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
    - name: install tauri-cli
      run: cargo install tauri-cli
    - name: Build
      run: cargo tauri build --verbose
    #- name: Run tests
      #run: cargo test --verbose
          
      
